"use strict";

module.exports = {
    SUCCESS_CODE: 200,
    ALLREADY_EXIST: 201,
    ERROR_CODE: 400,
    AUTH_CODE: 401,
    TOKEN_CODE: 417,
    SESSION_EXPIRED: "Your session is expired. Please login again to continue",
    TOKEN_ERROR: "Login token is Required",
    PROFILEIMAGE: "../backend/app/uploads/profileImages/",
    INCORRECT_FILE_TYPE: "Incorrect file type! Accepted file types are : jpg, jpeg, png, gif",
    INVALID_JSON: "Content Not Found",
    //LOGIN LOGS
    DEFAULT_PASSWORD: "123456",
    INVALID_TOKEN: "Token expired. Please login again",
    TOKEN_ERROR: "Login token is Required",
    LOGIN_SUCESS: "Logged In Successfully",
    INVALID_LOGIN: "Username or Password is not valid",
    ADDED_SUCCESS: "saved successfully",
    UPDATE_SUCCESS: "Updated Successfully",
    LOGGED_OUT: "User Logout Successfully",
    INVALID_EMAIL: "Email Not VALID",
    EMAIL_NOTIFICATION_SEND: "Email and SMS are sent successfully",
    DELETE_SUCCESS: "Deleted Successfully",
    FETCH_SUCCESS: "Fetched Successfully",
    SENT_SUCCESS: "Sent Successfully",
    CODE_EXPIRES: "Registeration Code Expires",
    FAILED_TO_PROCESS: "Failed to Process",
    NO_PROGRAM_ASSIGN: "No program assigned",
    SAME_SLEEP_SAVED_DAY: "Same Sleep Time Already saved for today",
    REQUIRED_FIELDS_MISSING: "Required Fields Missing",
    USER_ALREADY_EXIST: "User Already Exist. Please try with another user",
    PHONE_ALREADY_EXIST: "Phone number Already Exist. Please try with another number",
    CAT_ALREADY_EXIST: "Category Already Exist. Please try with another category",
    USER_DOEST_NOT_EXIST: "User Does not exist. Please register",
    INTERNAL_ERROR: "Internal Error",
    PROCESS_CALL: "You can start the call",
    NOT_A_TIME_TO_CALL: "You can only start call before 10 minutes of appointment",
    NOTIFICATION_SEND: "Notification Sent",
    INVALID_USER_TOKEN: "Invalid User Registration Link",
    NO_DATA_FOUND: "No data found",
    PAST_PATIENT_POINTS: "Fetched Successfully Past Patient Points",
    PAST_PATIENT_SLEEP_TRACKER_POINTS: "Fetched Past Sleep Tracker Successfully",
    PAST_PATIENT_ACTIVITY_TRACKER: "Fetched Past Activity Tracker Successfully",
    PAST_PATIENT_MOOD_TRACKER: "Fetched Past Mood Tracker Successfully",
    PAST_PATIENT_TRACKER_DATA: "Fetched Past Patient Tracker Data Successfully",
    DAILY_INFO_USEFUL: "Thank you for your feedback. We're glad you found this information useful. Please tell us what you liked about this content in the comments section below.",
    DAILY_INFO_NOT_USEFUL: "Thank you for your feedback. We're sorry you didn't find this information useful. Please tell us how we can improve this content in the comments section below.",
    ACCOUNT_TEMPORY_LOCK: "Your account is temporary locked. Please contact admin.",
    RESPONSE_RECORDED: "Thank you. Your response has been recorded.",
    SAVE_ACTIVITY:"Your activities have been saved",
    UPDATE_ACTIVITY:"Your activities have been saved",
    SAVE_SLEEP_TRACKER:"Your sleep has been saved",
    UPDATE_SLEEP_TRACKER:"Your sleep has been updated",
    KEY_WORD:"Keyword Already Exist. Please try with another keyword"
};